### ISSUE TITLE
Rajouter logo sur la landing page

### ISSUE THREAD

**Issue by AJuliette** [women-on-rails/ressources#2]
## Résumé de l'issue
Rajouter le logo de Women On Rails sur la landing page

## Situation actuelle
Il y a juste une présentation rapide du site Ressources et un call to action
<img width="1352" alt="Capture d’écran 2020-10-08 à 23 24 37" src="https://user-images.githubusercontent.com/42354334/95515153-71581900-09bd-11eb-95cc-07f67edcf430.png">

## Situation souhaitée
Rajouter le logo, comme sur [Tech Interview Handbook](https://yangshun.github.io/tech-interview-handbook/)
<img width="1345" alt="Capture d’écran 2020-10-08 à 23 29 34" src="https://user-images.githubusercontent.com/42354334/95515568-225eb380-09be-11eb-9f2c-4a0aabc00993.png">

## Informations complémentaires
- [ ] Enregistrer le logo au format `.jpeg` dans le dossier `website/static/img` (pour l'instant le logo n'est qu'au format `.ico`)
![logo_women_on_rails](https://user-images.githubusercontent.com/42354334/96772961-2c33de00-13e4-11eb-8a93-73bb31ddc623.jpeg)
- [ ] Ajouter le logo dans la page index: `website/src/pages/index.js`, juste au dessus du titre

Le site utilise `JSX`, voici un exemple d'ajout d'image:
```JSX
<img
  alt="Docusaurus with Keytar"
  src={useBaseUrl('img/docusaurus_keytar.svg')}
/>;
```

**Comment by Crysicia** [comment]
:wave: Hey, j'aimerais bien m'y mettre :)

**Comment by AJuliette** [comment]
Go for it !
