### ISSUE TITLE
Affichage de l'adresse mail en mode dark sur la page "Comment contribuer"

### ISSUE THREAD

**Issue by AJuliette** [women-on-rails/ressources#20]
# Issue pour un bug

## Description du bug
Image avec l'adresse mail en mode dark difficilement lisible sur la page `comment contribuer`.

## Comment le reproduire

Aller sur la page [comment contribuer](https://women-on-rails.github.io/ressources/docs/comment-contribuer) et passer en mode dark

## Situation voulue

@clodiap a réglé ce problème sur la page `help.js` pour laquelle elle a créé le component `DarkModeImage` où on peut mettre deux `src` selon le mode voulu (on a déjà un fichier `email.png` et `email_dark.png`)
Il faut donc: 
- [ ] importer le fichier du component dans le fichier `how-to-contribute`.
- [ ] ajouter le component dans le code avec les deux src différents

## Screenshots

<img width="776" alt="Capture d’écran 2020-10-19 à 14 41 40" src="https://user-images.githubusercontent.com/42354334/96452376-3a81ce80-1219-11eb-8314-3012b5e884a4.png">

## Contexte additionnel

On veut l'effet qui a déjà sur la page: [Qui sommes-nous ?](https://women-on-rails.github.io/ressources/help)
Pour t'aider, tu peux regarder comment c'est fait dans le fichier correspondant: `website/src/pages/help.js`

**Comment by morganbonhomme** [comment]
Hello, j'aimerai contribuer sur ce bug :)

**Comment by AJuliette** [comment]
Super, merci ! ❤️  Je t'ajoute en assignee
