### ISSUE TITLE
Faire un index pour les articles du blog

### ISSUE THREAD

**Issue by AJuliette** [women-on-rails/ressources#23]
# Issue pour une feature

## Résumé de l'issue
Refaire la mise en page de [l'index des articles du blog](https://women-on-rails.github.io/ressources/blog).

## Situation actuelle

Actuellement, l'index des articles du blog ressemble à ça:<br/>
<img width="1357" alt="Capture d’écran 2020-10-20 à 11 00 11" src="https://user-images.githubusercontent.com/42354334/96564423-6fe2f680-12c3-11eb-8962-c33969302654.png">

## Solution voulue

J'aime beaucoup ce design où on a une meilleur vision de tous les articles:<br/>
<img width="1272" alt="Capture d’écran 2020-10-20 à 11 01 39" src="https://user-images.githubusercontent.com/42354334/96564587-a3258580-12c3-11eb-82d0-42157a8492cb.png">
Donc un row avec des cards. La card comprend l'image de l'article, le titre, un résumé, la date, l'auteur / l'autrice. Le site n'est pas dynamique donc pas de tags. **edit: avec le thème des couleurs du site <3 + en fait si les tags c'est possible, c'est une option dans le header de l'article, à ajouter comme ça: `tags: [hello, docusaurus-v2]`** 

## Autre solution possible

Si tu as une autre idée pour le design, tu peux proposer en-dessous ! :)

## Informations complémentaires

- [x] Le site est construit avec Docusaurus, le thème de base est [Infima](https://facebookincubator.github.io/infima/docs/getting-started/introduction), il y a déjà des [modèles de card](https://facebookincubator.github.io/infima/docs/components/card) que tu peux styliser. Pareil, il y a un [système de grid](https://facebookincubator.github.io/infima/docs/layout/grid) très basique, mais qui suffit. Pour info, l'équipe de Docusaurus est en train de travailler sur l'implémentation du thème Bootstrap, mais ce n'est pas encore stable.
- [x] Tu peux faire un component `Card` à rajouter dans `website/src/components/ton_component.js`. Je te laisse regarder comment les components actuels sont écrits pour avoir un modèle
-  [ ] La page que tu vas faire ne seras pas `.mdx` mais en `.js`, il y en a deux actuellement comme ça sur le site: `website/src/pages/index.js`, `website/src/pages/help.js`, tu peux reprendre leur construction. Ce sont des pages en React.
- [ ] Il faudra changer la navbar qui est dans le fichier `website/docusaurus.config.js`, en enlevant le lien actuel vers le blog et en rajoutant le lien vers ta page, plus d'infos [ici](https://github.com/women-on-rails/ressources/blob/master/CONTRIBUTING.md#ajouter-dautres-%C3%A9l%C3%A9ments), la partie `Ajouter des éléments à la barre de navigation du haut`
- [ ] Il faudra également rajouter des illustrations aux deux articles déjà publiés, en utilisant [undraw](https://undraw.co/illustrations) par exemple ou tout autre banque d'images / d'illustrations dont tu as l'habitude :) Sur le fichier contributing, tu as une partie sur la [modification de fichiers](https://github.com/women-on-rails/ressources/blob/master/CONTRIBUTING.md#comment-modifier-du-contenu), en particulier `Comment éditer un article de blog existant`

N'hésite pas si tu as des remarques, des questions ou si quelque chose n'est pas assez précis !

**Comment by AJuliette** [comment]
@morganbonhomme Issue faite ;)

**Comment by morganbonhomme** [comment]
Thanks ! Je vais m'y mettre. J'ai checké la doc infima et vos pages en js, et j'ai une question : vous avez une classe ` padding-vert--md` dans `ressources/website/src/pages/index.js` ligne 16. Je ne la trouve ni dans le .css, ni dans la doc Infima, et ce n'est pas du bootstrap.  Est-ce que vous savez d'où elle vient ?

**Comment by clodiap** [comment]
Apparemment elle vient de Infima (`node_modules/infima/dist/css/default/default.css` et `node_modules/infima/dist/css/default-dark/default-dark.css`), j'ai fait une recherche dans mon éditeur ^^ : 
```css
.padding-vert--md {
      padding-bottom: 1rem !important;
      padding-top: 1rem !important;
    }
```

**Comment by morganbonhomme** [comment]
Thanks @clodiap !!

**Comment by morganbonhomme** [comment]
Je cherche comment importer automatiquement toutes les articles `.md` du blog qui sont dans `/ressources/website/blog` dans mon index des articles du blog (il s'agit d'une page `blog.js `avec le component card), je cherche depuis un moment mais la doc Docusaurus ne m'a pas éclairée + dans le [showcase](https://v2.docusaurus.io/showcase) je n'ai trouvé aucun site qui avait justement changé cet index du blog (ou alors sur un site externe). 
Du coup, je me demande si vous aviez eu l'idée car vous aviez des infos dessus ou des sources qui l'auraient fait ? 
Sinon il faudrait faire les cards (titre / résumé / auteur.rice / date / lien) directement dans le fichier .js et franchement je trouve pas ça ouf non ?

**Comment by morganbonhomme** [comment]
Sauf si vous prévoyez de ne pas faire des articles tous les jours auxquels cas, je peux toujours faire comme ça en attendant :)

**Comment by AJuliette** [comment]
Je suis en train de fouiller le code, [j'ai l'impression que ça c'est la page d'index des articles](https://github.com/facebook/docusaurus/blob/e4c1626106c4536a40ddef783eb0aebab5c0245b/packages/docusaurus-theme-classic/src/theme/BlogListPage/index.tsx)
Je pense que tu peux récupérer les articles grâce à `import type {Props} from '@theme/BlogPostItem';` ?
Je n'ai pas le temps de regarder plus avant ce soir, désolée >.<
Si ça te va de fouiller le code et démêler comment récupérer les articles, top, sinon effectivement en attendant on peut faire quelque chose de statique où on met nous même le titre, l'image, le lien, etc, c'est comme tu le sens :)
Bonus: en regardant la doc j'ai vu qu'il y avait des tags, donc en fait si on va pouvoir les mettre :p

**Comment by AJuliette** [comment]
(Si tu veux qu'on regarde ensemble, en attendant tu peux toujours designer la card avec des données bateau)

**Comment by morganbonhomme** [comment]
Je vais regarder plus en détail effectivement mais j'aurais pas le temps aujourd'hui :) Je verrai demain ! 
En attendant j'ai deux design : 

- Le premier avec l'auteur et en dessous sa version :hover  
![Capture d’écran 2020-10-20 à 17 25 55](https://user-images.githubusercontent.com/62025173/96609935-5cec1880-12fb-11eb-8966-482526ac5def.png)
![Capture d’écran 2020-10-20 à 17 25 59](https://user-images.githubusercontent.com/62025173/96609936-5e1d4580-12fb-11eb-8bd3-b8fce9af712a.png)

- Le deuxieme avec les tags et en dessous sa version :hover. Pas d'auteur sur cette card je trouvais que ca faisait beaucoup d'infos additionnelles, je ne sais pas ce que vous en pensez ? 
![Capture d’écran 2020-10-20 à 17 39 11](https://user-images.githubusercontent.com/62025173/96609939-5eb5dc00-12fb-11eb-99f0-bf76b6b01f11.png)
![Capture d’écran 2020-10-20 à 17 39 17](https://user-images.githubusercontent.com/62025173/96609941-5f4e7280-12fb-11eb-9b97-a863bd2f6ecd.png)

**Comment by morganbonhomme** [comment]
Après je ne sais pas si vous avez déjà une charte graphique concernant les couleurs du site, perso j'ai utilisé cette [palette](https://coolors.co/f6511d-4d6cfa-2e294e-1b998b-ffb400) là que je trouvais assez cool et dynamique, (où il y a bien la couleur verte primaire du site `#1B998B`)

**Comment by clodiap** [comment]
Ouah c'est joli :sparkles: Bravo :clap: 
Je crois que je préfère la 2ème, peut-être à cause de la petite touche de jaune du tag :heart_eyes:
Chouette la palette :smiley_cat: les couleurs sont chaudes et dynamiques

**Comment by AJuliette** [comment]
Hello ! J'aime bien pour le jaune du tag ! Et top l'hover !
Pour le nom, je préfère le garder, pour l'instant il n'y a que moi qui ait écrit mais ce que je souhaite c'est qu'il y ait plusieurs auteures donc mettre ça en avant sur l'index c'est important

**Comment by morganbonhomme** [comment]
Dac, je corrige ça et je regarde si je peux trouver comment automatiser

**Comment by morganbonhomme** [comment]
C'est ok pour vous comme ça ? 
Si ca vous va, je regarde comment personnaliser le dark mode car pour l'instant c'est pas fameux :)

![Capture d’écran 2020-10-21 à 13 01 15](https://user-images.githubusercontent.com/62025173/96711245-8a899e00-139d-11eb-98ae-53d79c6c564a.png)

**Comment by clodiap** [comment]
Ça me va :heart_eyes: :cat:

**Comment by AJuliette** [comment]
Super merci ! :)

**Comment by morganbonhomme** [comment]
@AJuliette j'ai un peu fouillé dans la doc pour automatiser mais je pense que ca va me prendre un peu de temps de bien comprendre. Est-ce qu'en attendant tu veux que je push l'index en statique avec les deux articles ?

**Comment by AJuliette** [comment]
C'est pas pressé comme il y a que deux articles. Mais si tu veux tu peux pusher, comme ça y aura déjà en ligne ton design (à ajouter peut-être sur ton portfolio que j'ai eu la curiosité de regarder et que je trouve très stylé!). Après tu pourras faire une autre issue et PR d'automatisation de l'index des articles :3
