### ISSUE TITLE
Passer les pages au format mdx pour une mise en page améliorée

### ISSUE THREAD

**Issue by clodiap** [women-on-rails/ressources#27]
## Résumé de l'issue

Il faudrait passer certaines pages au format mdx pour avoir une mise en page plus élaborée et pour pouvoir utiliser les `components` que l'on a déjà créés pour d'autres pages.

## Situation actuelle

Actuellement nous avons beaucoup de pages qui auraient besoin d'une mise en page moins linéaire, avec plus d'images et de liens, de petites `cards` et autres améliorations visuelles.

## Solution voulue

Des pages plus vivantes, avec des images et des `cards`, plus agréables à l'œil, qui donnent envie d'être lues :heart_eyes: .

Les pages suivantes seront à passer au format mdx. On cochera celles faites au fur et à mesure (pas besoin de les faire toutes tout d'un coup !)

Faire son profil en ligne :
- [x] CV
- [x] Portfolio
- [x] Blog
- [x] Ressources design

Trouver un job :
- [x] Les offres d'emplois
- [x] Le processus d'embauche
- [x] Les types de tests techniques : `docs/find_a_job/interview_types.md`
- [x] S'entraîner aux tests
- [ ] Questions techniques : `docs/find_a_job/technical_questions.md`

Pratiquer : 
- [ ] Réaliser un projet : `docs/practice/side-projects.md`
- [ ] L'open source : `docs/practice/open-source.md`

Se former et s'informer :
- [ ] Sites et outils ressources : `docs/keeping-up/.md`
- [ ] Blogs et newsletters : `docs/keeping-up/blogs-and-newsletters.md`
- [ ] Livres : `docs/keeping-up/books.md`
- [ ] Vidéos et Podcasts : `docs/keeping-up/videos-and-podcasts.md`

Rejoindre la communauté :
- [ ] Le réseau
- [ ] Les conférences 2020 : `docs/community/events.md`
- [ ] Personnes à suivre : `docs/community/people-to-follow.md`
- [ ] Transmettre : `docs/community/sharing.md`

## Informations complémentaires

Par exemple la page que @AJuliette  a modifiée : 

Avant : 
![katas-avant](https://user-images.githubusercontent.com/38593370/96616813-1ac6d500-1303-11eb-844e-1abcc20ab5c0.jpg)

Après : 
![katas-apres](https://user-images.githubusercontent.com/38593370/96616858-27e3c400-1303-11eb-9505-aacf7be50425.jpg)

**Comment by lordinatrice** [comment]
Je vais m'occuper du contenu de "Se former et s'informer" :)
