### ISSUE TITLE
Changer les images sur la page help (Qui sommes-nous ?) pour la version dark

### ISSUE THREAD

**Issue by AJuliette** [women-on-rails/ressources#3]
## Résumé de la demande
Les logos slack et meetup de la page `help.js` ont un fond blanc qui rend mal en version dark, il faut les remplacer

## Situation actuelle
<img width="1341" alt="Capture d’écran 2020-10-08 à 23 33 18" src="https://user-images.githubusercontent.com/42354334/95515903-a749cd00-09be-11eb-9706-567f5aa52967.png">

## Situation souhaitée
Remplacer les images slack et meetup par des images sans fond blanc pour que ça rende bien en mode dark

**Comment by clodiap** [comment]
Hello :)
Je veux bien m'en charger, il faudra aussi remplacer l'image avec l'email ?

**Comment by AJuliette** [comment]
Merci de proposer !
Pour l'image du mail, je ne l'ai pas incluse dans l'issue parce que je pensais qu'il faudrait carrément la rendre dynamique
=> quand le fond est noir, avoir une image qui a un fond noir et texte blanc et inversement pour le fond blanc.
Donc il faudrait que ça se fasse:
- au toggle dark / day 
- quand on navigue sur les pages, que ça lise dans quel état on est et récupérer le bon src d'image selon l'état

C'est du React, tu veux le faire sur cette issue ? Ou tu vois une autre solution ?

**Comment by clodiap** [comment]
Oui effectivement ce serait mieux en dynamique (peut-être même pour le logo slack qui n'est pas très visible en mode dark sans le fond), je vais regarder ça :) (je suis un peu rouillée en react mais c'est l'occasion de m'y remettre ^^)
Ok pour le faire sur cette issue :+1:

**Comment by AJuliette** [comment]
Top merci !

**Comment by AJuliette** [comment]
Fix mergé et déployé 🍾🍾🍾
