### ISSUE TITLE
Créer la page "Le processus d'embauche"

### ISSUE THREAD

**Issue by clodiap** [women-on-rails/ressources#41]
## Résumé de l'issue

Créer la page "Le processus d'embauche" en utilisant ce breadcrumb : [https://codepen.io/snookca/pen/qYoLaq](https://codepen.io/snookca/pen/qYoLaq)

## Situation actuelle

La page n'existe pas encore, elle se trouve dans les pages à faire : [Le processus d'embauche](https://github.com/women-on-rails/ressources/projects/3#card-47579586)

## Solution voulue

Une page avec une description sommaire de chaque étape du processus d'embauche.

Description du process courant d'embauche:
- appel
- tests techniques et retours
-  références
-  ce qu'attend le recruteur ou la recrutrice d'un entretien (technique ou de personnalité)
-  Après l'entretien (comment remercier / relancer)

## Informations complémentaires

Voici la copie d'écran du breadcrumb :
<img width="1096" alt="breadcrumb" src="https://user-images.githubusercontent.com/38593370/96895913-3bbb3180-148d-11eb-809e-88cd019c76fc.png">

**Comment by AJuliette** [comment]
<3

**Comment by AJuliette** [comment]
Issue mergée
