### ISSUE TITLE
Footer pas à sa place sur mobile sur la page "Qui sommes-nous ?"

### ISSUE THREAD

**Issue by AJuliette** [women-on-rails/ressources#5]
## Résumé de l'issue
🐛 Bug fix, vue sur mobile

## Situation actuelle
Sur la page "Qui sommes-nous ?" (`help.js`) sur mobile, le footer se met sur le texte: 
![121256201_347100056501395_6575545674713727251_n](https://user-images.githubusercontent.com/42354334/95687644-292b3780-0c05-11eb-9140-f7425910917c.png)

## Situation souhaitée
Que le footer reste en place en bas de la page è.é

## Ressources complémentaires 
Le site est sous version 2 de Docusaurus: https://v2.docusaurus.io/docs/
Il faudrait voir si ce n'est pas une issue qui a déjà été signalée sur leur repo: https://github.com/facebook/docusaurus/issues
Sinon, ils sont très réactifs sur leur Discord: https://discord.com/invite/Je6Ash6

**Comment by clodiap** [comment]
Hello :cat: 
Ça vient de la classe `h-100` appliquée au 1er div, cela centre le contenu de la page et fait en sorte que sa hauteur fasse un peu moins de 100% du viewport (la fenêtre du navigateur) et vu que la page est plus grande que les 100% du viewport, ça place les autres éléments en conséquence, le texte du haut de la page n'apparait plus et le footer se retrouve au niveau des 100% du viewport alors qu'il devrait se retrouver après le contenu, tout en bas. Je sais pas si c'est clair ^^
Je le corrige et je t'envoie une PR ?

**Comment by AJuliette** [comment]
Ahah d'accord, merci de l'explication !
J'ai rajouté la classe `h-100` parce que sinon en mode dark sur la landing page on avait une bande noire pas jolie.
Avant:
<img width="1370" alt="Capture d’écran 2020-10-18 à 09 09 59" src="https://user-images.githubusercontent.com/42354334/96360951-da5c3100-1121-11eb-9273-e7e4a67d4ffb.png">

Avec `h-100`
<img width="1363" alt="Capture d’écran 2020-10-18 à 09 09 31" src="https://user-images.githubusercontent.com/42354334/96360947-d6c8aa00-1121-11eb-9169-5ca73998d2da.png">

C'était un hot fix assez moche ^^ Je sais pas s'il faut juste enlever la classe de la page help vu qu'elle est assez grande maintenant ou si t'as une autre solution ? (oui, je fais toujours du CSS comme si je tapais sur deux bambous pour allumer du feu)

Et sinon si tu veux traiter une Issue, tu peux te marquer dessus et commencer ta PR 👍   (je suis en train de finaliser la doc pour préciser tout ça)

**Comment by clodiap** [comment]
Oui je pense qu'il faut uniquement l'enlever de la page help.js, pour l'instant elle ne gêne pas sur la home. Je vais regarder :smiley_cat: 

Pour se marquer sur une issue, ça marche comment ? On commente et on dit qu'on le fait ? (Désolée pour la question de newbie :joy: )

**Comment by AJuliette** [comment]
@clodiap Tu peux juste marquer comme là que tu voulais la faire et te mettre en assignee sur la droite (pareil pour une Pull Request)

<img width="277" alt="Capture d’écran 2020-10-18 à 14 23 27" src="https://user-images.githubusercontent.com/42354334/96367335-7f403380-114d-11eb-89f0-37dba82a46fd.png">

**Comment by AJuliette** [comment]
(pareil pour une Pull Request)

**Comment by AJuliette** [comment]
Merci pour les questions comme ça je précise la doc à chaque fois :3

**Comment by clodiap** [comment]
:smile: 
Ok ça marche, par contre on ne peut pas s'assigner d'issue (pas de petite roue crantée sur la droite) en tant que user normal, du coup faut juste commenter l'issue et linker l'issue dans la PR (j'avais oublié dans la dernière ^^)
![assignees-github](https://user-images.githubusercontent.com/38593370/96367775-2920bf80-1150-11eb-9a54-82acabd94fb7.png)

**Comment by AJuliette** [comment]
Ah mince oui bien sûr j'y avais pas pensé 🤦
Je te donne les droits d'écriture sur le repo, normalement comme ça ça sera bon (🍾 🥂 🎉)

<img width="238" alt="Capture d’écran 2020-10-18 à 15 01 15" src="https://user-images.githubusercontent.com/42354334/96368216-122f9c80-1153-11eb-8158-9a6189c1ddf4.png">

**Comment by clodiap** [comment]
Oh chouette merci :heart: :champagne: :clinking_glasses: :cat:  !
